security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers

    encoders:
        App\Entity\User: bcrypt

    providers:
        our_users:
            entity: {class: App\Entity\User, property: _username}

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            security: true

            guard:
                authenticators:
                    - app.security.login_form_authenticator
                entry_point: app.security.login_form_authenticator

            logout:
                path: /logout

            # This allows the user to login by submitting a username and password
            # Reference: https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                # The route name that the login form submits to
                check_path: security_login
                # The name of the route where the login form lives
                # When the user tries to access a protected page, they are redirected here
                login_path: security_login
                # Secure the login form against CSRF
                # Reference: https://symfony.com/doc/current/security/csrf_in_login_form.html
                csrf_token_generator: security.csrf.token_manager
                # The page users are redirect to when there is no previous page stored in the
                # session (for example when the users access directly to the login page).
                default_target_path: rte_homepage

                # This is the field name that you should give to the username field of your login form.
                # When you submit the form to check_path, the security system will look for a POST parameter with this name.
                # (type: string default: _username)
                username_parameter: 'email'
                password_parameter: 'password'

    #access_control:
         #- { path: ^/admin, roles: ROLE_ADMIN }
         #- { path: ^/profile, roles: ROLE_USER }
